//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmarproject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class multi_buy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public multi_buy()
        {
            this.multi_buy_list = new HashSet<multi_buy_list>();
        }
    
        public int multi_buy_id { get; set; }
        public string multi_buy_name { get; set; }
        public string raiser_id { get; set; }
        public int productid { get; set; }
        public System.DateTime raise_time { get; set; }
        public System.DateTime deadline { get; set; }
        public int maxamount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<multi_buy_list> multi_buy_list { get; set; }
        public virtual product product { get; set; }
    }
}
