//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmarproject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int order_detail_id { get; set; }
        public int order_id { get; set; }
        public string productname { get; set; }
        public int quiantity { get; set; }
        public decimal total_price { get; set; }
        public int productid { get; set; }
        public string sell_id { get; set; }
        public string category { get; set; }
        public string status { get; set; }
    
        public virtual order order { get; set; }
    }
}
