//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmarproject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.multi_buy = new HashSet<multi_buy>();
        }
    
        public int productid { get; set; }
        public string productname { get; set; }
        public decimal unitprice { get; set; }
        public int unitstock { get; set; }
        public string description { get; set; }
        public byte[] picture { get; set; }
        public string category { get; set; }
        public string category_multiple { get; set; }
        public string user_email { get; set; }
        public Nullable<int> sale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<multi_buy> multi_buy { get; set; }
    }
}
